# Global Options:
title = 'Daylam Tayari'
languageCode = 'en-us'
baseURL = 'https://tayari.gg/'
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
enableMissingTranslationPlaceholders = false
disableRSS = false
disableSitemap = false
disable404 = false
disableHugoGeneratorInject = false

# Theme Options:
theme = 'hello-friend-ng'

# Content Limit:
pagination.pagerSize = 10
rssLimit = 25

# Copyright:
copyright = "CC BY-NC-SA 4.0"

# Directories:
archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

# Build Settings:
buildDrafts  = false
buildFuture  = false
buildExpired = false

# Attributes:

[permalinks]
articles = "/articles/:section/:slug"
guides = "/guides/:section/:slug"
talks = "/talks/:slug"
writeups = "/writeups/:section/:slug"

[blackfriday]
hrefTargetBlank = true

[taxonomies]
categories = "categories"
tags = "tags"
pieces = "pieces"

[frontmatter]
   lastmod = ['lastmod']

# Markup:
[markup]
[markup.goldmark]
[markup.goldmark.extensions]
table=true
strikethrough=true
linkify=true
tasklist=true
gfm=true
footnote=true
typographer=false
[markup.goldmark.renderer]
unsafe=true

[params]
dateform = "January 2 2006"
dateformShort = "Jan 2 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02T15:04:05-0700"
# Metadata:
description = "Daylam Tayari :: Security | Coding | Linux"
keywords = ""
images = [""]
# Home page content:
homeSubtitle = "Security | Coding | Linux"
# External Content:
customCSS = []
customJS = []
justifyContent = true
# Theme:
enableThemeToggle = true
defaultTheme = "dark"
# Miscellaneous:
disableReadOtherPosts = false
enableSharingButtons = false
[params.author]
name = "Daylam Tayari"
[params.footer]
trademark = true
author = true
copyright = true
rss = true
topText = []
bottomText = []
[params.favicon.color]
mask = "#1b1c1d"
msapplication = "#1b1c1d"
theme = "#1b1c1d"
[params.logo]
logoHomeLink = "/"
logoMark = "$"
logoText = "/"
dynamic = true
logoCursorDisabled = false
logoCursorColor = "#aaaaaa"
# Social Links:
[[params.social]]
name = "resume"
url = "https://resume.tayari.gg"
[[params.social]]
name = "github"
url = "https://github.com/daylamtayari"
[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/daylamtayari"
[[params.social]]
name = "gpg"
url = "https://pgp.tayari.gg"
[[params.social]]
name = "email"
url = "mailto:daylam@tayari.gg"
# Menu
[menu]
[[menu.main]]
identifier = "articles"
name = "Articles"
url = "articles/"
[[menu.main]]
identifier = "guides"
name = "Guides"
url = "guides/"
[[menu.main]]
identifier = "talks"
name = "Talks"
url = "talks/"
[[menu.main]]
identifier = "about"
name = "About"
url = "about"
